//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int ReservaId { get; set; }
        public int UsuarioId { get; set; }
        public int PaqueteId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Estado { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
